services:
  - type: web
    name: myapp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && cd myapp && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: cd myapp && gunicorn myapp.wsgi:application
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.8
