services:
  - type: web
    name: myapp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && cd myapp && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn -w 3 -b 0.0.0.0:8080 myapp.wsgi:application --chdir myapp
    autoDeploy: true
